"""Convert an approved IntakeState into a schema-valid entry YAML."""
import os, yaml
from provenance import IntakeState, UNKNOWN

def _v(state, name, default=None):
    f = state.fields.get(name)
    if f is None or f.provenance == UNKNOWN or f.value is None:
        return default
    return f.value

def emit(state: IntakeState, out_dir="entries/"):
    entry = {
        "id": "ku-pending-00000000",   # real ID assigned by CI on merge
        "version": "0.1.0",
        "claim_type": _v(state, "claim_type", "real_null"),
        "evidence_layer": _v(state, "evidence_layer"),   # required — CI will reject if left None
        "domain": _v(state, "domain", "unspecified"),
        "title": _v(state, "title", "Untitled negative result"),
        "observation": _v(state, "observation", ""),
        "conditions": _v(state, "conditions", ""),
        "caveats": _v(state, "caveats", ""),
        "alternatives": _v(state, "alternatives", ""),
        "system": _v(state, "system", {}),
        "method": _v(state, "method", {"name": "unspecified"}),
        "confidence": {
            "level": _v(state, "confidence_level", "low"),
            "positive_control": _v(state, "positive_control", {"present": False,
                "detail": "not recorded during intake"}),
            "powered": _v(state, "powered"),
            "controls": _v(state, "controls", ""),
            "n": _v(state, "n", ""),
            "detection_limit": _v(state, "detection_limit", ""),
        },
        "related_positive": _v(state, "related_positive", []),
        "contributor": _v(state, "contributor", {"name": "unknown"}),
        "date": _v(state, "date", ""),
        "references": _v(state, "references", []),
    }
    os.makedirs(out_dir, exist_ok=True)
    # Comment header preserves which fields were left unknown, for reviewer context
    unknowns = state.unknowns()
    header = ("# Generated by conversational intake.\n"
              f"# Fields left UNKNOWN (honestly blank): {unknowns}\n"
              "# Review before opening a PR.\n\n")
    path = os.path.join(out_dir, "intake-draft.yaml")
    with open(path, "w") as f:
        f.write(header + yaml.safe_dump(entry, sort_keys=False, default_flow_style=False))
    return path
